ARM: tegra: tegra20: Fix mixed tabs-spaces indentation
Fix indentation and alignment when spaces were used instead of tabs.
This fixes checkpatch errors like:

    ERROR: code indent should use tabs where possible
    #306: FILE: arch/arm/boot/dts/tegra20-paz00.dts:306:
    +^I^I         <&tegra_car TEGRA20_CLK_PLL_P_OUT3>;$

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
Acked-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Signed-off-by: Thierry Reding <treding@nvidia.com>

[ upstream commit: 06d561ca0fa73a5b12ef6dfe0da7053e0ee37315 ]